name: zarply
run-name: ${{ gitea.actor }} has pushed
on:
  push:
    branches:  
      - '**'   ### this is done to prevent config runs when tagging

jobs:
  build-and-test:
    runs-on: workstation.ubuntu.lts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: print test
        run: echo "This is a test message"
  
  clean_containers:
    needs: flake8-linting
    runs-on: workstation.ubuntu.lts
    steps:
      - name: Stop Docker Containers and Uvicorn
        run: |
          docker ps -a
          docker image ls
          docker stop $(docker ps -a -q) || true
          docker rm $(docker ps -a -q) || true
          docker image prune -f || true # shellcheck disable=SC2046
          docker volume rm $(docker volume ls --format "{{.Name}}") || true
          docker network prune -f || true
          pid=$(sudo lsof -t -i:8000) || true
          sudo kill $pid || true
          pid=$(sudo lsof -t -i:8001) || true
          sudo kill $pid || true

# example of testing pipline 
  # flutter_test:
  #   runs-on: workstation.ubuntu.lts
  #   container:
  #     image: gitea.cyber-mint.com/pumppay/pp-flutter:latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Verify Flutter installation
  #       run: flutter doctor -v

  #     - name: Run Flutter Tests
  #       run: flutter test


      
